### ISSUE TITLE
PIXELARITY makes Pocophone F1 with Pixel Experience almost unusable

### ISSUE THREAD

**Issue by EfficiencyVI** [Magisk-Modules-Repo/PIXELARITY#4]
After installation when ever I wake up the phone the display is so dark that it is barely usable. After 5 to 10 tries it sometimes works to restore the right brightness. Disabling auto brightness made it a bit better but it is still annoying.

However uninstalling PIXELARITY makes the phone get stuck on reboot on the second boot screen. I'm not sure how to fix this. Phone is is a Pocophone F1 with latest Pixel Experience Beryllium.

**Comment by Kyliekyler** [comment]
Oof I haven't read this before I update, but  uninstall is fixed tho. Make sure to update first then flash the same module in magisk or ur recovery

**Comment by EfficiencyVI** [comment]
I have to wait for the TWRP/Magisk Module. Then I can tell you if it worked.

**Comment by Kyliekyler** [comment]
Update now on v3.6 it was fixed already. After installing v3.6, u need to reflash it again for uninstallation.

**Comment by EfficiencyVI** [comment]
After reinstalling from Magisk and uninstalling from TWRP everything works fine again. Thank you.
